### PR TITLE
Update private-data-ldn-application.md

### PR DESCRIPTION
**Pull request by dkkapur**
Adding in Galen's feedback

### CODE REVIEW

**Comment by dkkapur** [comment]
Thoughts on this? Just wondering if this is becoming too redundant to the actual LDN application with the questions on SPs?

**Comment by dkkapur** [comment]
Will open up a separate Issue to propose merging this - let's discuss in governance call before merging.

**Comment by jessie8o8** [comment]
Hi Deep! Great work on identifying the common questions and information needed. I love forms and standardization.

I would like to give suggestions to 3 points in the template
> Why is it useful to Filecoin
- I know the answer to this can be somewhat undefined but we do have a general idea of what this "usefulness" means to us. If we are familiar with this idea, we should make it familiar to the client applying too.  


>Which SPs will you/the data owner be working with to store the data?

This implies that the SPs should be chosen out before applying for an LDN and may hinder a client from applying if it is not completed yet. I would suggest at description below like so 
`If SPs have not been chosen out yet, after submission, please edit and update the form as they are chosen out. If you need support on finding reputable SPs, please view the filgram.io or filecoin slack channels: #fil-plus, #fil-deal-market`
Not only does this address a client's lack of SPs but also guides them toward appropriate action in the absences of SPs.


> Notaries that support the project

Same sentiment as above. This implies that they need notary support lined up before applying for an LDN and may hinder a client from applying if it is not completed yet. If I were a client with genuine data that wants to onboard it to Filecoin, this question would make me feel lost. I would suggest a description like so:
`Notaries preform KYC/KYC to validate the legitimacy of data and organizations. To find supporting notaries please view the list of [round 3 notaries](https://github.com/filecoin-project/notary-governance/tree/main/notaries) and the Filecoin slack channel #fil-plus-application-review and update the form as you gain support. `
This would address the lack of notaries and guide them towards appropriate action in the absences of notaries.

**Comment by MegTei** [comment]
HI @dkkapur Is this a tactical/ temporary process while the E-Fil is still a WIP?

**Comment by dkkapur** [comment]
Thanks - incorporated the feedback from @jessie8o8. @raghavrmadya can you review?

**Review by raghavrmadya — APPROVED** [review]

**Pull request merged**
